# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50ed5a031464847282a4036495440a00f59ff2133839a3d818ecf5816071bea6fa65cefbe27a315ccf10af53f516289dab0f0febb0e743e29d33b799a0b575b2

test:
  secret_key_base: cd4d501db6ff8d2b592ba1bd6f0d4dcbb2a20f56362aca47fedb36b4e537efdede89aa05751aaae8ff2362898aae95a2e9e4b9b7884a773087d2a06f84b63dd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
